"""Add user roles

Revision ID: e847c20f2122
Revises: 4add3279b475
Create Date: 2024-09-19 18:55:34.753219

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e847c20f2122"
down_revision: Union[str, None] = "4add3279b475"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Define the roleenum type
role_enum = postgresql.ENUM("MANAGER", "DEVELOPER", name="roleenum")


def upgrade() -> None:
    role_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("role", role_enum, nullable=False, server_default="DEVELOPER"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
    role_enum.drop(op.get_bind())
